services:
  ollama:
    image: ollama/ollama:latest
    container_name: Temp-2
    restart: unless-stopped

    ports:
      - "58003:11434"

    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:
    name: oracle-practice-ollama-data
