services:
  oracle-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oracle-agent
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no"
    volumes:
      - ../trajectories:/app/trajectories
    # networks:
    #   - oracle-practice-net

# networks:
#   oracle-practice-net:
#     external: true
